baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Theme #3 Prototype'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
